
package com.ipartek.formacion.webservice;

import javax.jws.WebMethod;
import javax.jws.WebResult;
import javax.jws.WebService;
import javax.jws.soap.SOAPBinding;
import javax.xml.bind.annotation.XmlSeeAlso;
import javax.xml.ws.Action;
import com.ipartek.formacion.webservice.interfaces.CursoArray;
import com.ipartek.formacion.webservice.interfaces.CursoList;
import com.ipartek.formacion.webservice.interfaces.ObjectFactory;


/**
 * This class was generated by the JAX-WS RI.
 * JAX-WS RI 2.2.9-b130926.1035
 * Generated source version: 2.2
 * 
 */
@WebService(name = "CursoWS", targetNamespace = "http://interfaces.webservice.formacion.ipartek.com/")
@SOAPBinding(style = SOAPBinding.Style.RPC)
@XmlSeeAlso({
    ObjectFactory.class
})
public interface CursoWS {


    /**
     * 
     * @return
     *     returns com.ipartek.formacion.webservice.interfaces.CursoArray
     */
    @WebMethod
    @WebResult(partName = "return")
    @Action(input = "http://interfaces.webservice.formacion.ipartek.com/CursoWS/getAllRequest", output = "http://interfaces.webservice.formacion.ipartek.com/CursoWS/getAllResponse")
    public CursoArray getAll();

    /**
     * 
     * @return
     *     returns com.ipartek.formacion.webservice.interfaces.CursoList
     */
    @WebMethod
    @WebResult(partName = "return")
    @Action(input = "http://interfaces.webservice.formacion.ipartek.com/CursoWS/getAllListaRequest", output = "http://interfaces.webservice.formacion.ipartek.com/CursoWS/getAllListaResponse")
    public CursoList getAllLista();

}
