
package com.ipartek.formacion.webservice;

import java.net.MalformedURLException;
import java.net.URL;
import javax.xml.namespace.QName;
import javax.xml.ws.Service;
import javax.xml.ws.WebEndpoint;
import javax.xml.ws.WebServiceClient;
import javax.xml.ws.WebServiceException;
import javax.xml.ws.WebServiceFeature;


/**
 * This class was generated by the JAX-WS RI.
 * JAX-WS RI 2.2.9-b130926.1035
 * Generated source version: 2.2
 * 
 */
@WebServiceClient(name = "CursoWSImplService", targetNamespace = "http://webservice.formacion.ipartek.com/", wsdlLocation = "http://localhost:8080/JavaWeb/cursows?wsdl")
public class CursoWSImplService
    extends Service
{

    private final static URL CURSOWSIMPLSERVICE_WSDL_LOCATION;
    private final static WebServiceException CURSOWSIMPLSERVICE_EXCEPTION;
    private final static QName CURSOWSIMPLSERVICE_QNAME = new QName("http://webservice.formacion.ipartek.com/", "CursoWSImplService");

    static {
        URL url = null;
        WebServiceException e = null;
        try {
            url = new URL("http://localhost:8080/JavaWeb/cursows?wsdl");
        } catch (MalformedURLException ex) {
            e = new WebServiceException(ex);
        }
        CURSOWSIMPLSERVICE_WSDL_LOCATION = url;
        CURSOWSIMPLSERVICE_EXCEPTION = e;
    }

    public CursoWSImplService() {
        super(__getWsdlLocation(), CURSOWSIMPLSERVICE_QNAME);
    }

    public CursoWSImplService(WebServiceFeature... features) {
        super(__getWsdlLocation(), CURSOWSIMPLSERVICE_QNAME, features);
    }

    public CursoWSImplService(URL wsdlLocation) {
        super(wsdlLocation, CURSOWSIMPLSERVICE_QNAME);
    }

    public CursoWSImplService(URL wsdlLocation, WebServiceFeature... features) {
        super(wsdlLocation, CURSOWSIMPLSERVICE_QNAME, features);
    }

    public CursoWSImplService(URL wsdlLocation, QName serviceName) {
        super(wsdlLocation, serviceName);
    }

    public CursoWSImplService(URL wsdlLocation, QName serviceName, WebServiceFeature... features) {
        super(wsdlLocation, serviceName, features);
    }

    /**
     * 
     * @return
     *     returns CursoWS
     */
    @WebEndpoint(name = "CursoWSImplPort")
    public CursoWS getCursoWSImplPort() {
        return super.getPort(new QName("http://webservice.formacion.ipartek.com/", "CursoWSImplPort"), CursoWS.class);
    }

    /**
     * 
     * @param features
     *     A list of {@link javax.xml.ws.WebServiceFeature} to configure on the proxy.  Supported features not in the <code>features</code> parameter will have their default values.
     * @return
     *     returns CursoWS
     */
    @WebEndpoint(name = "CursoWSImplPort")
    public CursoWS getCursoWSImplPort(WebServiceFeature... features) {
        return super.getPort(new QName("http://webservice.formacion.ipartek.com/", "CursoWSImplPort"), CursoWS.class, features);
    }

    private static URL __getWsdlLocation() {
        if (CURSOWSIMPLSERVICE_EXCEPTION!= null) {
            throw CURSOWSIMPLSERVICE_EXCEPTION;
        }
        return CURSOWSIMPLSERVICE_WSDL_LOCATION;
    }

}
